# Gems that should be installed at the system level

source :rubygems

# IRB replacement
gem "pry"

# print helpers
gem "awesome_print"
gem "colored"

# Git helpers
gem "git"
gem "git-smart"
gem "gist"

# Dev frameworks
gem "sinatra"
gem "jekyll"
gem "rails"

# Testing
gem "rspec"

# Utility apps
gem "cloudapp"
