tap 'gfontenot/formulae'
tap 'thoughtbot/formulae'

cask 'alacritty'
cask 'postgres'

brew 'asdf'
brew 'bat'
brew 'carthage'
brew 'coreutils'
brew 'ctags'
brew 'extract_url'
brew 'fzf'
brew 'gfontenot/formulae/xcode-cli'
brew 'gh'
brew 'git'
brew 'gnupg'
brew 'haskell-stack'
brew 'jq'
brew 'neovim'
brew 'pinentry-mac'
brew 'the_silver_searcher'
brew 'thoughtbot/formulae/gitsh'
brew 'thoughtbot/formulae/rcm'
brew 'tmux'
brew 'tree'
brew 'zsh'
