# Taps
tap gfontenot/gitupdate
tap jingweno/gh

# System stuff
install zsh
install git --without-completions
install gh
install macvim

# rbenv and plugins
install rbenv
install ruby-build
install rbenv-binstubs
install rbenv-default-gems
install rbenv-gem-rehash
install rbenv-aliases

# Objective-C Development
install class-dump
install mogenerator

# Email
install msmtp
install mutt
install mbsync
install notmuch
install urlview
install contacts
install lynx
install gpg2

# Misc
install heroku-toolbelt
install the_silver_searcher
install haskell-platform
install git-update

## ----------------------------
#      OS X Applications
## ----------------------------

tap phinze/homebrew-cask

install brew-cask

cask install adium
cask install alfred
cask install bartender
cask install delivery-status
cask install dropbox
cask install iterm2
cask install kaleidoscope
cask install moom
cask install netnewswire
cask install omnifocus
cask install quickradar
cask install rdio
cask install sim-pholders
cask install sonos
cask install transmission
