# Taps
tap gfontenot/gitupdate
tap jingweno/gh

# System stuff
install zsh
install git --without-completions
install git-update
install gh
install macvim

# rbenv and plugins
install rbenv
install ruby-build
install rbenv-binstubs
install rbenv-default-gems
install rbenv-gem-rehash
install rbenv-aliases

# Objective-C Development
install class-dump

# Email
install msmtp
install mutt
install mbsync
install notmuch
install urlview
install contacts
install lynx
install gpg2

# Misc
install heroku-toolbelt
install the_silver_searcher
install haskell-platform
