# Taps
tap gfontenot/gitupdate
tap jingweno/gh

# System stuff
install zsh
install git --without-completions
install git-update
install gh
install macvim

# rbenv and plugins
install chruby
install ruby-install

# Objective-C Development
install class-dump

# Email
install mutt
install mbsync
install notmuch
install urlview
install contacts
install lynx
install gpg2

# Misc
install heroku-toolbelt
install the_silver_searcher
install haskell-platform
