#!/bin/sh
#
# pbrisbin 2014 - details:
#
# - http://blog.adamspiers.org/2014/10/05/managing-your-github-notifications-inbox-with-mutt/
# - https://github.com/aspiers/mutt.pub/blob/master/bin/read-github-notification
# - https://github.com/pbrisbin/dotfiles/blob/bdebae88aaaa6bf69012324d8e74f424c32a508b/tag-scripts/local/bin/gh-read
#
###

# Decoding the HTML part seems to put arbitrary line breaks in the middle of the
# beacon URL. This function just prints stdin as one long line.
beacon_re='https://github\.com/notifications/beacon/.*\.gif'
beacon_url="$(xargs printf -- "%s" | grep -o "$beacon_re")"

[ -n "$beacon_url" ] && curl --silent "$beacon_url" >/dev/null &
