# prevent collisions with personal scripts
local-bin-path: /Users/gordon/.stack/bin

extra-include-dirs:
  - /opt/homebrew/opt/openssl@3/include
  - /opt/homebrew/opt/libpq/include
extra-lib-dirs:
  - /opt/homebrew/opt/openssl@3/lib
  - /opt/homebrew/opt/libpq/lib

templates:
  params:
    author-email: gordon@fonten.io
    author-name: Gordon Fontenot
    github-username: gfontenot
