" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Inconsolata:h13       " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
" set lines=25 columns=100          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar
set guioptions-=T                 " Hide toolbar.


