" Make sure Vundle is running before anything else
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

set rtp+=~/.config/vim

for fpath in split(globpath('~/.config/vim', '*.vim'), '\n')
  exec 'source' fpath
endfor

call vundle#end()

colorscheme lucius                " Use Lucius for our color scheme
LuciusDark                        " Use the dark version of Lucius

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set noswapfile                    " Don't use swapfiles

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs

set wrap                          " Turn on line wrapping.
