#!/usr/bin/env sh

set -e

echo "\n==========================================="
echo "Setting up Mail\n"

echo "Creating temp directory for mutt"
mkdir ~/.mutt/temp || echo "Temp directory exists"

echo "Pulling mail"
mbsync -a

echo "indexing mail with notmuch"
notmuch new
