# shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/Code/dotfiles

# your project folder that we can `c [tab]` to
export PROJECTS=~/Code

# Where you keep your plain text notes
export NOTES="$HOME/Dropbox (Personal)/notes"

# source every .zsh file in this repo
for config_file ($DOTFILES/**/source/*.zsh) [[ "$(basename $config_file)" == "completion.zsh" ]] || source $config_file

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

# load every completion after autocomplete loads
for config_file ($DOTFILES/**/source/completion.zsh) source $config_file

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
