#!/bin/bash

set -e

echo ""
echo "==========================================="
echo "Installing additional alacritty files"
echo ""

if ! [[ -r ~/.terminfo/61/alacritty ]]; then
  echo "Installing alacritty terminfo"
  alacritty_terminfo=$(mktemp)
  curl -o "$alacritty_terminfo" https://raw.githubusercontent.com/jwilm/alacritty/master/extra/alacritty.info
  tic -xe alacritty,alacritty-direct "$alacritty_terminfo"
fi

if ! [[ -r /usr/local/share/man/man1/alacritty.1.gz ]]; then
  echo "Installing alacritty man pages"
  sudo mkdir -p /usr/local/share/man/man1
  alacritty_manpages=$(mktemp)
  curl -o "$alacritty_manpages" https://raw.githubusercontent.com/jwilm/alacritty/master/extra/alacritty.man
  gzip -c "$alacritty_manpages" | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
fi
