#!/usr/bin/env sh

set -e

echo ""
echo "==========================================="
echo "Removing OS X's bullshit path helper"
echo ""

sudo rm /etc/zprofile \
  || echo "Path helper already deleted"
