#!/usr/bin/env sh

set -e

echo "\n==========================================="
echo "Setting up Homebrew\n"

echo "Installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
  || echo "Homebrew already installed"

echo "chown-ing /usr/local"
sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local

echo "Installing brew bundle"
brew tap Homebrew/bundle

echo "Installing homebrew dependencies"

find . -type f -iname "Brewfile" -print0 | while IFS= read -r -d $'\0' line; do
  echo "\n------------------"
  echo "Installing dependencies from $line"
  brew bundle --file="$line" \
    || echo "Some dependencies failed, attempting to continue"
done
