#!/bin/sh

set -e

echo ""
echo "==========================================="
echo "Setting up Homebrew"
echo ""

echo "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
  || echo "Homebrew already installed"

eval "$(/opt/homebrew/bin/brew shellenv)"

echo "Installing homebrew dependencies"
brew bundle
