#!/usr/bin/env sh

set -e

echo ""
echo "==========================================="
echo "Setting up Vim"
echo ""

echo "Installing vim plugins"
vim +PlugInstall +qa

echo "Creating undo directory"
mkdir -p ~/.vim/undo || echo "Undo directory exists"
