#!/usr/bin/env sh

set -e

echo "Installing Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim \
  || echo "Vundle already installed"

echo "Installing vim plugins"
vim +PluginInstall +qa

