#!/usr/bin/env sh

set -e

echo ""
echo "==========================================="
echo "Setting up Mutt"
echo ""

echo "Creating temp directory for mutt"
mkdir ~/.mutt/temp || echo "Temp directory exists"

echo "Pulling mail"
mbsync -a
