#!/bin/sh

echo ""
echo "==========================================="
echo "Setting up the asdf version manager"
echo ""

# asdf itself is installed via homebrew

echo "Installing language plugins"

# Add language plugins

asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf plugin-add elm https://github.com/asdf-community/asdf-elm.git
