#!/usr/bin/env sh

set -e

echo ""
echo "==========================================="
echo "Setting up Haskell"
echo ""

echo "Installing basic dependencies"
stack install alex happy yesod-bin hoogle
