#!/usr/bin/env sh

templates_dir="$HOME/Library/Developer/Xcode/Templates/File Templates"

echo "Creating file templates directory"
mkdir "$templates_dir"

echo "Installing file templates"
find $(pwd)/tag-xcode/source/templates/* -type d -maxdepth 0 -print0 | while IFS= read -r -d $'\0' line; do
  echo "Installing $line"
  ln -s "$line" "$templates_dir"
done
