#!/bin/sh

set -e

echo ""
echo "==========================================="
echo "Starting LaunchAgents"
echo ""

find ~/Library/LaunchAgents -iname "*.plist" -print0 | while IFS= read -r -d $'\0' line; do
  echo "Starting $line"
  launchctl load "$line"
done
