#!/usr/bin/env sh

set -e

echo "\n==========================================="
echo "Setting up Vim\n"

echo "Installing vim plugins"
vim +PlugInstall +qa

echo "Creating undo directory"
mkdir -p ~/.vim/undo || echo "Undo directory exists"
