#!/usr/bin/env sh

set -e

echo "\n==========================================="
echo "Setting up Vim\n"

echo "Installing Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim \
  || echo "Vundle already installed"

echo "Installing vim plugins"
vim +PluginInstall +qa

echo "Creating undo directory"
mkdir -p ~/.vim/undo || echo "Undo directory exists"
