#!/usr/bin/env sh

set -e

echo "\n==========================================="
echo "Setting up Xcode\n"

templates_dir="$HOME/Library/Developer/Xcode/Templates/File Templates"

echo "Creating file templates directory"
mkdir "$templates_dir" || echo "File Templates directory exists"

echo "Installing file templates"
find $(pwd)/tag-xcode/Templates/* -type d -maxdepth 0 -print0 | while IFS= read -r -d $'\0' line; do
  echo "Installing $line"
  ln -s "$line" "$templates_dir" || echo "Template already linked"
done
