matches:

  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ";dstamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: ";stamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d%H%M%S"

  # Print the output of a shell command
  - trigger: ";furl"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "$HOME/.local/bin/current-url"
